### ISSUE TITLE
CropType is pad, therefore we can´t use focalpoint

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.ImagePicker#14]
Se this https://github.com/skybrud/Skybrud.ImagePicker/blob/master/src/Skybrud.ImagePicker/Models/ImagePickerImage.cs#L34

**Comment by abjerner** [comment]
@Ornhoj any problems with our frontend if we change `mode` from `pad` to `crop`?

I think we once settled on `pad` as default, and then the frontend would switch to `crop` instead if needed in a particular context.

The problem is however that information about the anchor or focal point isn't included in the URL when `mode` is `pad` as the image then isn't cropped, but only resized/padded.

Or would it be better to skip the `cropUrl` property entirely, and then return the focal point through a new property instead? Then the frontend will have all the information needed to concatenate the URL.

**Comment by Ornhoj** [comment]
Future development should properly support both cases, but for know change the mode - it will be a non-breaking change

**Comment by abjerner** [comment]
@rpjengaard new release is here: https://github.com/skybrud/Skybrud.ImagePicker/releases/tag/v2.0.0-alpha002

I've only changed the mode from `pad` to `crop` for now. I haven't included information about the focal point in it's own property, which we'd want for the future - so I'll leave the issue open until I have the time to look into that ;)
